### ISSUE TITLE
Negative margin does not appear to be working

### ISSUE THREAD

**Issue by rmnaderdev** [argentini/Argentini.Sfumato#1]
When I use a negative margin like in tailwind: `-ml-px` does not seem to work. 

Docs: https://tailwindcss.com/docs/margin#using-negative-values

Using something like `-m-[10px]` also does not work.

![image](https://github.com/argentini/Argentini.Sfumato/assets/7833468/00385b1c-b279-48f1-b4d1-ce3adccbea8a)

**Comment by argentini** [comment]
This has been added in version 5.0.57.
