### ISSUE TITLE
Watcher randomly crashes during development

### ISSUE THREAD

**Issue by rmnaderdev** [argentini/Argentini.Sfumato#2]
While editing and changing Razor partials/views and applying changes in Rider, I notice that my changes are not being applied only to find that the watcher had crashed with this exception:
```
Project file changes detected at 19:04:40.668
⏵ Updated .\Views\Partials\_PlatformHeader.cshtml at 19:04:40.668
Project file changes detected at 19:04:40.669
⏵ Updated .\Views\Partials\_PlatformHeader.cshtml at 19:04:40.669
Project file changes detected at 19:04:40.669
⏵ Updated .\Views\Partials\_PlatformHeader.cshtml at 19:04:40.669
Project file changes detected at 19:04:40.669
⏵ Updated .\Views\Partials\_PlatformHeader.cshtml at 19:04:40.669
⏵ Generated .\wwwroot\stylesheets\application.css (28.3kb, +base, +120 utilities) in 0.060s
Completed build of 1 CSS file (28.3kb) in 0.061s

Watching; Press ESC to Exit

Unhandled exception. System.ArgumentException: The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair`2[] array, Int32 index)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at Argentini.Sfumato.Program.Main(String[] args) in /Users/magic/Developer/Argentini.Sfumato/Argentini.Sfumato/Program.cs:line 195
   at Argentini.Sfumato.Program.<Main>(String[] args)
```

I am still not able to pinpoint exactly what causes this issue or how to reliably reproduce the issue. I would imagine it is caused when the .NET process is using the file on save.

**Comment by argentini** [comment]
That line is a simple foreach statement iterating through a ConcurrentDictionary. I'm guessing that it is changing during the iteration. I'm going to try cloning the dictionary to a collection and iterate that in isolation. I also have to handle removing the items from the dictionary in a concurrency-friendly way when it's done. I'll let you know when I have an update to pull.

**Comment by argentini** [comment]
Update to version 5.0.58 and give that a try. I added mitigations to what I believe the problem to be.

**Comment by rmnaderdev** [comment]
I will test it and let you know if the issue comes up again.

**Comment by argentini** [comment]
Looks like this has been solved. Closing the issue.
