### ISSUE TITLE
Flexbox shrink classes don't appear to work

### ISSUE THREAD

**Issue by rmnaderdev** [argentini/Argentini.Sfumato#3]
When using the `shrink` and `shrink-0` classes documented in tailwind here: https://tailwindcss.com/docs/flex-shrink#dont-shrink

Sfumato does not seem to add any classes for these styles to the css. 
![image](https://github.com/argentini/Argentini.Sfumato/assets/7833468/2e246d32-1bdb-4b46-b694-eab8e2abee70)

**Comment by argentini** [comment]
@PotatoDotJar thanks for finding this! The problem also affected flex grow utilities. Both have been fixed in 5.0.59.
