### ISSUE TITLE
basis-full breaks stylesheet

### ISSUE THREAD

**Issue by rmnaderdev** [argentini/Argentini.Sfumato#4]
When using the `basis-full` class. The scss file fails to compile.

Example:
`<div class="basis-full  md:basis-1/2 lg:basis-1/3 " ...>...</div>`

Causes this issue:
![image](https://github.com/argentini/Argentini.Sfumato/assets/7833468/f18606e5-2872-4b0b-926f-001a7d23b30b)

![image](https://github.com/argentini/Argentini.Sfumato/assets/7833468/61016b0a-3595-414a-85a4-46dcd0f4be54)

After removing `basis-full`, the sheet compiles again.

**Comment by argentini** [comment]
This has been fixed in 5.0.60
