### ISSUE TITLE
basis-0 does not appear to work

### ISSUE THREAD

**Issue by rmnaderdev** [argentini/Argentini.Sfumato#5]
When trying to use the `basis-0` class defined in tailwind here: https://tailwindcss.com/docs/flex-basis, the style is not applied.

Currently running sfumato v5.0.66

![image](https://github.com/argentini/Argentini.Sfumato/assets/7833468/fba2c5b1-1677-4453-9e88-5f20726193cf)

**Comment by argentini** [comment]
@PotatoDotJar this is fixed in 5.0.67, which should be available shortly.
