### ISSUE TITLE
Cannot position elements center using transform

### ISSUE THREAD

**Issue by rmnaderdev** [argentini/Argentini.Sfumato#6]
While trying to position elements in the center of a container using `fixed` or `absolute`, `fixed top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2` does not give the desired outcome. 

![image](https://github.com/argentini/Argentini.Sfumato/assets/7833468/3f4a9de2-db33-492c-82cc-7376802a30e9)

`-translate-x-1/2 -translate-y-1/2` are not parsed as negative values and so `translate(var(--sf-translate-x), var(--sf-translate-y))` is computed as `translate(50%, 50%)` instead of the desired `translate(-50%, -50%)`.

Furthermore, when trying to use `translate-x-[-50%] translate-y-[-50%]`, only the `translate-x-[-50%]` is applied.
![image](https://github.com/argentini/Argentini.Sfumato/assets/7833468/4f8bfbf1-6136-4ec7-b357-8af4f110df93)

**Comment by argentini** [comment]
Sfumato has a centering translate utility to make this simpler; try this: `relative top-1/2 left-1/2 translate-center`

You could also use arbitrary CSS, like: `[transform:translate(-50%,-50%)]`

I'm pushing an update that fixes:

- fraction utilities will process negative prefixes (e.g. `-translate-x-1/2`)
- translate-x arbitrary value (e.g. `translate-x-[-50%]`) is fixed

**Comment by argentini** [comment]
OK, version 5.0.68 is available.
