### ISSUE TITLE
New line issue in entry scss file

### ISSUE THREAD

**Issue by rmnaderdev** [argentini/Argentini.Sfumato#7]
In the main scss file, not having a new line under `@sfumato utilities` prevents sfumato from resolving class styles.

This does not work:
```scss
@sfumato base;
@sfumato utilities;
```

This does work:
```scss
@sfumato base;
@sfumato utilities;
 
```

In the first example, not having a new line under the utilities line will not resolve classes and the `@sfumato utilities;` text will be appended to the css output file.

![image](https://github.com/argentini/Argentini.Sfumato/assets/7833468/3d7e7512-1589-404a-a869-d065d8f03541)

**Comment by argentini** [comment]
This has been resolved in version 5.0.74. I also merged in your change which supports redirected input in watch mode.
